<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="p" nsPrefix="">
  <eClassifiers xsi:type="ecore:EClass" name="A" eSuperTypes="#//sub/D #//B #//C">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ref" eType="#//C"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="B" eSuperTypes="#//sub/D"/>
  <eClassifiers xsi:type="ecore:EClass" name="C"/>
  <eSubpackages name="sub">
    <eClassifiers xsi:type="ecore:EClass" name="D"/>
  </eSubpackages>
</ecore:EPackage>
